import type { Metadata } from 'next';

import { LayoutFooter } from '~/components/layout/layout-footer';
import { LayoutHeader } from '~/components/layout/layout-header';

import './globals.css';

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <LayoutHeader />

        <main className="min-h-screen">
          { children }
        </main>

        <LayoutFooter />
      </body>
    </html>
  );
}
