/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
// Query TypeMap
import '@sanity/client';

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  aspectRatio?: number;
  height?: number;
  width?: number;
};

export type SanityFileAsset = {
  _createdAt: string;
  _id: string;
  _rev: string;
  _type: 'sanity.fileAsset';
  _updatedAt: string;
  altText?: string;
  assetId?: string;
  description?: string;
  extension?: string;
  label?: string;
  mimeType?: string;
  originalFilename?: string;
  path?: string;
  sha1hash?: string;
  size?: number;
  source?: SanityAssetSourceData;
  title?: string;
  uploadId?: string;
  url?: string;
};

export type Geopoint = {
  _type: 'geopoint';
  alt?: number;
  lat?: number;
  lng?: number;
};

export type ImageBanner = {
  _type: 'imageBanner';
  backgroundImage: {
    _type: 'image';
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    crop?: SanityImageCrop;
    hotspot?: SanityImageHotspot;
  };
  buttonLink?: string;
  buttonText?: string;
  description?: string;
  layout?: 'left' | 'right';
  title?: string;
};

export type ExecutiveBoard = {
  _type: 'executiveBoard';
  description?: string;
  members?: Array<{
    _key: string;
    _type: 'member';
    image: {
      _type: 'image';
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      crop?: SanityImageCrop;
      hotspot?: SanityImageHotspot;
    };
    memberID: string;
    name: string;
    position: string;
  }>;
  title?: string;
};

export type ProductHighlight = {
  _type: 'productHighlight';
  bakcgroundImage: {
    _type: 'image';
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    crop?: SanityImageCrop;
    hotspot?: SanityImageHotspot;
  };
  description?: string;
  products?: Array<{
    _key: string;
    _type: 'product';
    image?: {
      _type: 'image';
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      crop?: SanityImageCrop;
      hotspot?: SanityImageHotspot;
    };
    link?: string;
  }>;
  title?: string;
};

export type InfoBreakdown = {
  _type: 'infoBreakdown';
  breakdowns?: Array<{
    _key: string;
    _type: 'breakdown';
    icon?: IconPicker;
    image?: {
      _type: 'image';
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      crop?: SanityImageCrop;
      hotspot?: SanityImageHotspot;
    };
    text?: string;
  }>;
  image: {
    _type: 'image';
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    crop?: SanityImageCrop;
    hotspot?: SanityImageHotspot;
  };
  title?: string;
};

export type Gallery = {
  _type: 'gallery';
  images?: Array<{
    _key: string;
    _type: 'image';
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    crop?: SanityImageCrop;
    hotspot?: SanityImageHotspot;
  }>;
  title?: string;
};

export type ArticleHighlight = {
  _type: 'articleHighlight';
  article: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'article';
  };
  pretitle?: string;
};

export type InfoBlock = {
  _type: 'infoBlock';
  backgroundColor?: Color;
  image: {
    _type: 'image';
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    crop?: SanityImageCrop;
    hotspot?: SanityImageHotspot;
  };
  position?: 'left' | 'right';
  quote?: string;
  text?: Array<{
    _key: string;
    _type: 'block';
    children?: Array<{
      _key: string;
      _type: 'span';
      marks?: Array<string>;
      text?: string;
    }>;
    level?: number;
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      _key: string;
      _type: 'link';
      href?: string;
    }>;
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
  }>;
  title?: string;
};

export type InfoTiles = {
  _type: 'infoTiles';
  backgroundImage?: {
    _type: 'image';
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    crop?: SanityImageCrop;
    hotspot?: SanityImageHotspot;
  };
  tiles?: Array<{
    _key: string;
    _type: 'tile';
    icon?: IconPicker;
    image?: {
      _type: 'image';
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      crop?: SanityImageCrop;
      hotspot?: SanityImageHotspot;
    };
    text?: string;
  }>;
  title?: string;
};

export type HeroBannerText = {
  _type: 'heroBannerText';
  backgroundColor?: Color;
  backgroundImage?: {
    _type: 'image';
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    crop?: SanityImageCrop;
    hotspot?: SanityImageHotspot;
  };
  gradientColor?: Color;
  pretitle?: string;
  pretitleIcon?: IconPicker;
  subtitle?: string;
  textHorizontalPosition?: 'left' | 'middle' | 'right';
  textVerticalPosition?: 'bottom' | 'middle' | 'top';
  title?: string;
};

export type FullSpanMedia = {
  _type: 'fullSpanMedia';
  gradientColor?: Color;
  image?: {
    _type: 'image';
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    crop?: SanityImageCrop;
    hotspot?: SanityImageHotspot;
  };
  video?: string;
};

export type Divider = {
  _type: 'divider';
  type?: 'type0' | 'type1' | 'type2' | 'type3' | 'type4';
};

export type RecentArticles = {
  _type: 'recentArticles';
  articles: Array<{
    _key: string;
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'article';
  }>;
  title?: string;
  type?: 'dark' | 'light';
};

export type HighlightCard = {
  _type: 'highlightCard';
  cards?: Array<{
    _key: string;
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'article';
  }>;
};

export type HeroBannerCarousel = {
  _type: 'heroBannerCarousel';
  carousel: Array<{
    _key: string;
    _type: 'carouselItem';
    backgroundImage: {
      _type: 'image';
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      crop?: SanityImageCrop;
      hotspot?: SanityImageHotspot;
    };
    link: string;
    mapImage?: {
      _type: 'image';
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      crop?: SanityImageCrop;
      hotspot?: SanityImageHotspot;
    };
    pretitle?: string;
    subtitle?: string;
    summarySubtitle: string;
    summaryText: string;
    summaryTitle: string;
    title: string;
  }>;
};

export type PortableText = Array<{
  _key: string;
  _type: 'block';
  children?: Array<{
    _key: string;
    _type: 'span';
    marks?: Array<string>;
    text?: string;
  }>;
  level?: number;
  listItem?: 'bullet' | 'number';
  markDefs?: Array<{
    _key: string;
    _type: 'link';
    href?: string;
  }>;
  style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
}>;

export type Article = {
  _createdAt: string;
  _id: string;
  _rev: string;
  _type: 'article';
  _updatedAt: string;
  image: {
    _type: 'image';
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    crop?: SanityImageCrop;
    hotspot?: SanityImageHotspot;
  };
  title: string;
  url: Slug;
};

export type Page = {
  _createdAt: string;
  _id: string;
  _rev: string;
  _type: 'page';
  _updatedAt: string;
  components?: Array<{
    _key: string;
  } & ArticleHighlight | {
    _key: string;
  } & Divider | {
    _key: string;
  } & ExecutiveBoard | {
    _key: string;
  } & FullSpanMedia | {
    _key: string;
  } & Gallery | {
    _key: string;
  } & HeroBannerCarousel | {
    _key: string;
  } & HeroBannerText | {
    _key: string;
  } & HighlightCard | {
    _key: string;
  } & ImageBanner | {
    _key: string;
  } & InfoBlock | {
    _key: string;
  } & InfoBreakdown | {
    _key: string;
  } & InfoTiles | {
    _key: string;
  } & ProductHighlight | {
    _key: string;
  } & RecentArticles>;
  title: string;
  url: Slug;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  bottom?: number;
  left?: number;
  right?: number;
  top?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  height?: number;
  width?: number;
  x?: number;
  y?: number;
};

export type SanityImageAsset = {
  _createdAt: string;
  _id: string;
  _rev: string;
  _type: 'sanity.imageAsset';
  _updatedAt: string;
  altText?: string;
  assetId?: string;
  description?: string;
  extension?: string;
  label?: string;
  metadata?: SanityImageMetadata;
  mimeType?: string;
  originalFilename?: string;
  path?: string;
  sha1hash?: string;
  size?: number;
  source?: SanityAssetSourceData;
  title?: string;
  uploadId?: string;
  url?: string;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  id?: string;
  name?: string;
  url?: string;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  blurHash?: string;
  dimensions?: SanityImageDimensions;
  hasAlpha?: boolean;
  isOpaque?: boolean;
  location?: Geopoint;
  lqip?: string;
  palette?: SanityImagePalette;
};

export type MediaTag = {
  _createdAt: string;
  _id: string;
  _rev: string;
  _type: 'media.tag';
  _updatedAt: string;
  name?: Slug;
};

export type Slug = {
  _type: 'slug';
  current: string;
  source?: string;
};

export type IconPicker = {
  _type: 'iconPicker';
  name?: string;
  provider?: string;
  svg?: string;
};

export type Color = {
  _type: 'color';
  alpha?: number;
  hex?: string;
  hsl?: HslaColor;
  hsv?: HsvaColor;
  rgb?: RgbaColor;
};

export type RgbaColor = {
  _type: 'rgbaColor';
  a?: number;
  b?: number;
  g?: number;
  r?: number;
};

export type HsvaColor = {
  _type: 'hsvaColor';
  a?: number;
  h?: number;
  s?: number;
  v?: number;
};

export type HslaColor = {
  _type: 'hslaColor';
  a?: number;
  h?: number;
  l?: number;
  s?: number;
};

export type AllSanitySchemaTypes = Article | ArticleHighlight | Color | Divider | ExecutiveBoard | FullSpanMedia | Gallery | Geopoint | HeroBannerCarousel | HeroBannerText | HighlightCard | HslaColor | HsvaColor | IconPicker | ImageBanner | InfoBlock | InfoBreakdown | InfoTiles | MediaTag | Page | PortableText | ProductHighlight | RecentArticles | RgbaColor | SanityAssetSourceData | SanityFileAsset | SanityImageAsset | SanityImageCrop | SanityImageDimensions | SanityImageHotspot | SanityImageMetadata | SanityImagePalette | SanityImagePaletteSwatch | Slug;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: src/sanity/query/sanity.fetcher.ts
// Variable: pageQuery
// Query: *[_type == 'page' && url.current == $url][0] {      ...,      components[] {        ...,        _type == 'recentArticles' => {          ...,          articles[]->        }      }    }
export type PageQueryResult = {
  _createdAt: string;
  _id: string;
  _rev: string;
  _type: 'page';
  _updatedAt: string;
  components: Array<{
    _key: string;
    _type: 'articleHighlight';
    article: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'article';
    };
    pretitle?: string;
  } | {
    _key: string;
    _type: 'divider';
    type?: 'type0' | 'type1' | 'type2' | 'type3' | 'type4';
  } | {
    _key: string;
    _type: 'executiveBoard';
    description?: string;
    members?: Array<{
      _key: string;
      _type: 'member';
      image: {
        _type: 'image';
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        crop?: SanityImageCrop;
        hotspot?: SanityImageHotspot;
      };
      memberID: string;
      name: string;
      position: string;
    }>;
    title?: string;
  } | {
    _key: string;
    _type: 'fullSpanMedia';
    gradientColor?: Color;
    image?: {
      _type: 'image';
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      crop?: SanityImageCrop;
      hotspot?: SanityImageHotspot;
    };
    video?: string;
  } | {
    _key: string;
    _type: 'gallery';
    images?: Array<{
      _key: string;
      _type: 'image';
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      crop?: SanityImageCrop;
      hotspot?: SanityImageHotspot;
    }>;
    title?: string;
  } | {
    _key: string;
    _type: 'heroBannerCarousel';
    carousel: Array<{
      _key: string;
      _type: 'carouselItem';
      backgroundImage: {
        _type: 'image';
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        crop?: SanityImageCrop;
        hotspot?: SanityImageHotspot;
      };
      link: string;
      mapImage?: {
        _type: 'image';
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        crop?: SanityImageCrop;
        hotspot?: SanityImageHotspot;
      };
      pretitle?: string;
      subtitle?: string;
      summarySubtitle: string;
      summaryText: string;
      summaryTitle: string;
      title: string;
    }>;
  } | {
    _key: string;
    _type: 'heroBannerText';
    backgroundColor?: Color;
    backgroundImage?: {
      _type: 'image';
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      crop?: SanityImageCrop;
      hotspot?: SanityImageHotspot;
    };
    gradientColor?: Color;
    pretitle?: string;
    pretitleIcon?: IconPicker;
    subtitle?: string;
    textHorizontalPosition?: 'left' | 'middle' | 'right';
    textVerticalPosition?: 'bottom' | 'middle' | 'top';
    title?: string;
  } | {
    _key: string;
    _type: 'highlightCard';
    cards?: Array<{
      _key: string;
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'article';
    }>;
  } | {
    _key: string;
    _type: 'imageBanner';
    backgroundImage: {
      _type: 'image';
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      crop?: SanityImageCrop;
      hotspot?: SanityImageHotspot;
    };
    buttonLink?: string;
    buttonText?: string;
    description?: string;
    layout?: 'left' | 'right';
    title?: string;
  } | {
    _key: string;
    _type: 'infoBlock';
    backgroundColor?: Color;
    image: {
      _type: 'image';
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      crop?: SanityImageCrop;
      hotspot?: SanityImageHotspot;
    };
    position?: 'left' | 'right';
    quote?: string;
    text?: Array<{
      _key: string;
      _type: 'block';
      children?: Array<{
        _key: string;
        _type: 'span';
        marks?: Array<string>;
        text?: string;
      }>;
      level?: number;
      listItem?: 'bullet' | 'number';
      markDefs?: Array<{
        _key: string;
        _type: 'link';
        href?: string;
      }>;
      style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal';
    }>;
    title?: string;
  } | {
    _key: string;
    _type: 'infoBreakdown';
    breakdowns?: Array<{
      _key: string;
      _type: 'breakdown';
      icon?: IconPicker;
      image?: {
        _type: 'image';
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        crop?: SanityImageCrop;
        hotspot?: SanityImageHotspot;
      };
      text?: string;
    }>;
    image: {
      _type: 'image';
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      crop?: SanityImageCrop;
      hotspot?: SanityImageHotspot;
    };
    title?: string;
  } | {
    _key: string;
    _type: 'infoTiles';
    backgroundImage?: {
      _type: 'image';
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      crop?: SanityImageCrop;
      hotspot?: SanityImageHotspot;
    };
    tiles?: Array<{
      _key: string;
      _type: 'tile';
      icon?: IconPicker;
      image?: {
        _type: 'image';
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        crop?: SanityImageCrop;
        hotspot?: SanityImageHotspot;
      };
      text?: string;
    }>;
    title?: string;
  } | {
    _key: string;
    _type: 'productHighlight';
    bakcgroundImage: {
      _type: 'image';
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      crop?: SanityImageCrop;
      hotspot?: SanityImageHotspot;
    };
    description?: string;
    products?: Array<{
      _key: string;
      _type: 'product';
      image?: {
        _type: 'image';
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        crop?: SanityImageCrop;
        hotspot?: SanityImageHotspot;
      };
      link?: string;
    }>;
    title?: string;
  } | {
    _key: string;
    _type: 'recentArticles';
    articles: Array<{
      _createdAt: string;
      _id: string;
      _rev: string;
      _type: 'article';
      _updatedAt: string;
      image: {
        _type: 'image';
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        crop?: SanityImageCrop;
        hotspot?: SanityImageHotspot;
      };
      title: string;
      url: Slug;
    }>;
    title?: string;
    type?: 'dark' | 'light';
  }> | null;
  title: string;
  url: Slug;
} | null;
declare module '@sanity/client' {
  interface SanityQueries {
    '\n    *[_type == \'page\' && url.current == $url][0] {\n      ...,\n      components[] {\n        ...,\n        _type == \'recentArticles\' => {\n          ...,\n          articles[]->\n        }\n      }\n    }\n  ': PageQueryResult;
  }
}
